apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-backend
  template:
    metadata:
      labels:
        app: kube-backend
    spec:
      priorityClassName: "high-priority"
      volumes:
        - name: kube-backend-metrics
          persistentVolumeClaim:
            claimName: kube-backend-volume
      containers:
        - name: kube-backend
          image: sklrsn/kube-backend:latest
          readinessProbe:
            httpGet:
              path: "/api/v1/health"
              port: 9090
          livenessProbe:
            httpGet:
              path: "/api/v1/health"
              port: 9090
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "64Mi"
              cpu: "250m"
          ports:
            - containerPort: 9090
          env:
            - name: DB_HOST
              value: kube-postgres-service
            - name: DB_PASSWORD
              value: password # use secrets, not this way
            - name: REDIS_HOST
              value: kube-redis-service
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: password # use secrets, not this way
          volumeMounts:
            - name: kube-backend-metrics
              mountPath: /opt/backend/stats
