apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-pvc
spec:
  resources:
    requests:
      storage: 10Mi
  accessModes:
    - ReadWriteMany
  storageClassName: shared
  volumeName: kube-pv
