apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-ingress
  labels:
    name: kube-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: kube-frontend-service
                port:
                  number: 8080
          - pathType: Prefix
            path: /api/
            backend:
              service:
                name: kube-backend-service
                port:
                  number: 9090
