apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-pvc
spec:
  resources:
    requests:
      storage: 10Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  volumeName: kube-pv
