apiVersion: v1
kind: Service
metadata:
  name: kube-welcome-service
spec:
  selector:
    app: kube-welcome-pod
  type: NodePort
  ports:
    - port: 3050
      targetPort: 8080
      nodePort: 31515
