services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    environment:
      - DB_HOST=postgres-server
      - DB_PASSWORD=password
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
    depends_on:
      - postgres-server
      - redis-server
    restart: always

  postgres-server:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password

  redis-server:
    image: redis:7.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass password