services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - backend
      - frontend
    restart: always

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    environment:
      - DB_HOST=postgres-server
      - DB_PASSWORD=password
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
    depends_on:
      - postgres-server
      - redis-server
    restart: always

  postgres-server:
    build:
      context: postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=password

  redis-server:
    build:
      context: redis
      dockerfile: Dockerfile
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass password